"""add_notifications_and_auth_hardening

Revision ID: 276fa78d6847
Revises: 51dd12f83ae5
Create Date: 2026-05-22 23:22:26.381403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276fa78d6847'
down_revision: Union[str, None] = '51dd12f83ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
