"""add_notifications_and_auth_hardening

Revision ID: 51dd12f83ae5
Revises: cd29137e28b4
Create Date: 2026-05-22 22:01:07.286411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dd12f83ae5'
down_revision: Union[str, None] = 'cd29137e28b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_inactivity_email_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('wants_email_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'wants_email_notifications')
    op.drop_column('users', 'last_inactivity_email_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'verification_expires_at')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
